export const FETCH_REPO_START = 'FETCH_REPO_START';
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_START';
export const FETCH_REPO_FAIL = 'FETCH_REPO_START';

export const SET_TABLE_DATA = 'SET_TABLE_DATA';