export const FETCH_REPO_START = 'FETCH_REPO_START';
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS';
export const FETCH_REPO_FAILED = 'FETCH_REPO_FAILED';

export const SET_TABLE_DATA = 'SET_TABLE_DATA';

export const SET_SEARCHED_WORD = 'SET_SEARCHED_WORD';

export const SET_LOCAL_TABLEDATA = 'SET_LOCAL_TABLEDATA';
